[package]
name = "tectyl"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
crossterm = { version = "0.27", features = ["event-stream"] }

futures = "0.3"
tokio = { version = "1.35", features = ["full"] }
